title: Yusuf Abdulle
url: "https://yabdulle.github.io"

markdown: kramdown

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Publications"
   link: "/publications/"
 - name: "Teaching & Talks"
   link: "/ta/"
 - name: "CV"
   link: "/cv.pdf"

social:
 - name: "Email"
   link: "mailto:yusuf.abdulle@kcl.ac.uk"
 - name: "GitHub"
   link: "https://github.com/yabdulle"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/yusufab/"
